### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by josdejong** [stackp/promisejs#18]
Thanks for this library.

It would be great if promisejs could be installed via [npm](http://npmjs.org). Bower would be useful too but I don't personally need that.

**Comment by hanifbbz** [comment]
+1

**Comment by ccnokes** [comment]
+1

**Comment by tunnckoCore** [comment]
@josdejong @hanifbbz @ccnokes you definitely should use some other [better library from here ](https://github.com/promises-aplus/promises-spec/blob/master/implementations.md)

[ayepromise](https://github.com/cburgmer/ayepromise) and [zolmeister](https://github.com/zolmeister/promiz) are good hits. Promiz is pretty fast, in top 4-6 in both Petka's benchmarks.

@stackp ping-pong?

**Comment by stackp** [comment]
Thanks for your comment. I'm not convinced publishing on npm would be a good idea. This project does not follow the Promises/A+ standard, which did not exist at the time.
