### ISSUE TITLE
please add a license

### ISSUE THREAD

**Issue by cstoehr** [stackp/promisejs#25]

**Comment by stackp** [comment]
There is a license: https://github.com/stackp/promisejs/blob/master/promise.js#L3

Do you mean it should be in the README ?

**Comment by bodorjzsolt** [comment]
I would recommend to add a license text. The text from the OSI or SPDX is OK of course, but maybe you would change the template to "Neither the name of Pierre Duquesne nor the names of its contributors" , like in other projects.
