### ISSUE TITLE
How can I chain ajax requests?

### ISSUE THREAD

**Issue by peshoicov** [stackp/promisejs#29]
I want to achieve something like this:

`promise.chain([

```
promise.get('some-url-1'),

promise.get('some-url-2'),

promise.get('some-url-3')
```

]).then(

```
function(err, n) {

    // get the responses here .. 

}
```

);`

Can you advise please.

**Comment by stackp** [comment]
Hi peshoicov, you probably want to use join() since you're not using the result of a previous call in the following ones:

```
promise.join([
    promise.get('/'),
    promise.get('/')
]).then(function(results) {
    console.log(results);
});
```

If for whatever reason you really want sequential execution, you have to pass a list of functions that return a promise:

```
promise.chain([
  function() {return promise.get('/');},
  function() {return promise.get('/');}
]).then(function(err, res) {
  console.log(res);
});
```
