### ISSUE TITLE
How to access response headers

### ISSUE THREAD

**Issue by se1exin** [stackp/promisejs#30]
Sorry if this has been answered but could not find by searching..

I need to access a custom response header (Date) in my ajax calls, how do I go about this?

**Comment by se1exin** [comment]
Sorry if this has been answered but could not find by searching..

I need to access a custom response header (Date) in my ajax calls, how do I go about this?

**Comment by se1exin** [comment]
Figured it out: - use `xhr.getResponseHeader('Date')`

``` javascript
promise.get(this.path, params, {"Accept": "application/json"})
    .then(function(error, response, xhr) {
         var date = xhr.getResponseHeader('Date');
});
```

**Comment by stackp** [comment]
Indeed!
