### ISSUE TITLE
Is this still being looked upon?

### ISSUE THREAD

**Issue by iKevinShah** [stackp/promisejs#32]
Hi all,

Like the title says, is this library still being looked upon? 
If so, I was testing out "promises" based functionality of my js on personal blog.  Everything else works as one would expect however, the promise.post fails to pass on `new FormData("myFormElement");`

Now when its all text based, I can serialize and send it in data field. But my form data also has images / pdfs which I upload and that is not being received by the server and neither is it being sent (confirming that based on console checks and network tabs).

I checked the source and I see `payload = _encode(data);`.

Any help?

Code I am using:

```
<form name="submitnewcontent" id="myForm" method="post" action="/submit">
    <input type="text" name="Text" title="title" />
    <br />
    <input name="fileu" type="file" accept="image/*">
    <br/>
    <input type="submit" value="Go" id="submitbutton" />
</form>
<script>
$('#submitbutton').onclick(function(){
promise.post('/z/index.php',new FormData(document.getElementById("myForm")));
});
<script>
```

**Comment by stackp** [comment]
Indeed, it does not support FormData, you would have to extract the parameters like so:

```
var formData = new FormData(document.getElementById("myForm"));
var params = {};

formData.forEach(function(value, key){
    params[key] = value;
});

promise.post('/z/index.php', params);
```

**Comment by iKevinShah** [comment]
so no way for POSTing images unless I am mistaken.
